### ISSUE TITLE
[Chain Dev] - Deploy Contract on zkEVM test network 

### ISSUE THREAD

**Issue by t-bello7** [t-bello7/mlh-hackthon#3]
- Deploy contract on the zkEVM test network
@Quojo-Steve  steps to achieve this

### Get free eth on zkev test network
- Add the following networks manually to meta mask
![Screenshot from 2023-08-27 06-41-36](https://github.com/t-bello7/mlh-hackthon/assets/24270269/cd8f65ec-e89b-4135-ac79-949e07eeb852)
[Screencast from 27-08-2023 06:42:51.webm](https://github.com/t-bello7/mlh-hackthon/assets/24270269/08f499fd-1b12-4468-8099-a7de6448dc22)
- Get free eth from this link
https://faucet.polygon.technology/
- Follow the procedure from the faucet link to join the 0xpolygon devs discord server

### Bridge gorlie network to zkev test network
This is more like transfering from a network to another
- Get free eth on gorlie network by mining for it in this link
https://goerli-faucet.pk910.de/#/claim/ea69b1ed-d192-436a-b819-92f4fe2cccb1
- After getting free eth you can then bridge the networks. You can follow this documentation - https://wiki.polygon.technology/docs/zkevm/bridge-to-zkevm/

**Comment by Quojo-Steve** [comment]
On it!

**Comment by t-bello7** [comment]
I would be sending a PR to close this issue.
